// Code generated by raindrop build, DO NOT EDIT.
export interface Env {
  AI: Ai;
  CURRENCY_API_KEY: string;
  GROQ_API_KEY: string;
  NEWS_API_KEY: string;
  SAMBANOVA_API_KEY: string;
  WEATHER_API_KEY: string;
}
